name: release

on:
  release:
    types: [published]

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Cache Go
      id: go-cache
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys:
          ${{ runner.os }}-go-

    - name: test
      run: |
        sudo apt install -y bash libpcap-dev jq
        make test-host

    - name: Login to ghcr.io
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: vcr-bot
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
